project:
  type: website
  output-dir: docs

website:
  title: "Data Infrastructure Group"
  description: "We investigate the infrastructures powering the data that powers the world."
  navbar:
    right:
      - text: Research
        href: research.qmd
      - text: Work With Us
        href: collaborate.qmd
      - icon: github
        href: https://github.com/datainfrastructuregroup


  google-analytics: <Insert your ID here>
  cookie-consent: true


format:
  html:
    theme:
      - united
    css: includes/styles.css

editor: visual

